package com.auru.betterme

const val API_KEY = "4d579f8bbc5144fbfb49514ff034e06f"
const val API_LANGUAGE = "en"
const val API_START_POSITION = 1
const val MOVIES_NUMBER_LIMIT = 10000
const val MOVIES_PERSIST_PORTION_NUMBER = 1000
const val MOVIES_FAVOURITE_CRITICAL_NUMBER = MOVIES_PERSIST_PORTION_NUMBER
